name: defulat_paramter
test_ratio: 0.3
max_len : 100
hyper_parameters:
  epochs: 10
  batch_size: 50
  learning_rate: 0.001
  embedding: 128
  cnn_filters: 100
  kernel_size:
      - 3
      - 4
      - 5
  dropout: 0.5
  hidden_units: 100
