batch_size: 1024
epochs: 10
max_len : 100
hyper_parameters:
  cnn_filters: 128
  dropout: 0.5
  embed_input: 104680
  embedding: 128
  hidden_units: 1024
  kernel_size:
    - 3
    - 4
    - 5
  out_dim: 2
learning_rate: 0.001
mode: token
model: cnn-basic
dataset: nsmc
name: nsmc_token
test_file_path: ../dataset/nsmc/ratings_test.txt
test_ratio: 0
train_file_path: ../dataset/nsmc/ratings_train.txt
train_name: 토큰화!
