batch_size: 1000
dataset: nsmc
epochs: 10
hyper_parameters:
  cnn_filters:
  - 256
  - 256
  - 256
  - 256
  - 256
  - 256
  dropout: 0.5
  embed_input: 3006
  embedding: 1000
  hidden_units: 2048
  kernel_size:
  - 7
  - 7
  - 3
  - 3
  - 3
  - 3
  max_pools:
  - 3
  - 3
  - 0
  - 0
  - 0
  - 3
  out_dim: 2
learning_rate: 0.001
max_len: 100
mode: char
model: char-cnn-basic
name: nsmc_char_custom
test_file_path: ../dataset/nsmc/ratings_test.txt
test_ratio: 0.2
train_file_path: ../dataset/nsmc/ratings_train.txt
train_name: custom char
