dataset: nsmc
hyper_parameters:
  batch_size: 1024
  cnn_filters: 128
  dropout: 0.5
  embedding: 128
  epochs: 10
  hidden_units: 512
  kernel_size:
  - 3
  - 4
  - 5
  learning_rate: 0.0001
max_len: 100
mode: token
model: BasicCnnClassification
name: nsmc_tokens
test_ratio: 0.3
